export const students = [
  { id: "HS001", name: "Đào Quý An",                    class: "11A3" },
  { id: "HS002", name: "Nguyễn Tiến Anh",               class: "11A3" },
  { id: "HS003", name: "Phan Nguyễn Duy Anh",           class: "11A3" },
  { id: "HS004", name: "Nguyễn Nhật Thanh Bình",        class: "11A3" },
  { id: "HS005", name: "Phạm An Bảo Châu",              class: "11A3" },
  { id: "HS006", name: "Đinh Chí Duy",                  class: "11A3" },
  { id: "HS007", name: "Lê Thái Duy",                   class: "11A3" },
  { id: "HS008", name: "Đặng Lê Tùng Dương",            class: "11A3" },
  { id: "HS009", name: "Nguyễn Đỗ Thành Đạt",           class: "11A3" },
  { id: "HS010", name: "Lưu Hương Giang",               class: "11A3" },
  { id: "HS011", name: "Danh Quốc Hào",                 class: "11A3" },
  { id: "HS012", name: "Võ Ngọc Hân",                   class: "11A3" },
  { id: "HS013", name: "Thị Ngọc Thanh Thu Hiền",       class: "11A3" },
  { id: "HS014", name: "Huỳnh Tấn Hiệp",                class: "11A3" },
  { id: "HS015", name: "Trần Phi Hiệp",                 class: "11A3" },
  { id: "HS016", name: "Kiều Đỗ Tấn Hưng",              class: "11A3" },
  { id: "HS017", name: "Lê Thị Thùy Hương",             class: "11A3" },
  { id: "HS018", name: "Nguyễn Hoàng Khang",            class: "11A3" },
  { id: "HS019", name: "Đào Thị Ái Linh",               class: "11A3" },
  { id: "HS020", name: "Trần Minh Long",                class: "11A3" },
  { id: "HS021", name: "Phan Gia Lộc",                  class: "11A3" },
  { id: "HS022", name: "Nguyễn Hoàng Minh",             class: "11A3" },
  { id: "HS023", name: "Trần Gia Bảo Minh",             class: "11A3" },
  { id: "HS024", name: "Nguyễn Phương Nam",             class: "11A3" },
  { id: "HS025", name: "Đỗ Hoàng Bảo Ngọc",             class: "11A3" },
  { id: "HS026", name: "Nguyễn Thành Nhân",             class: "11A3" },
  { id: "HS027", name: "Đỗ Nguyễn Uyên Như",            class: "11A3" },
  { id: "HS028", name: "Nguyễn Phong",                  class: "11A3" },
  { id: "HS029", name: "Lê Hữu Phúc",                   class: "11A3" },
  { id: "HS030", name: "Phạm Nguyễn Như Quỳnh",         class: "11A3" },
  { id: "HS031", name: "Đặng Đức Thắng",                class: "11A3" },
  { id: "HS032", name: "Nguyễn Văn Tình",               class: "11A3" },
  { id: "HS033", name: "Nguyễn Thế Toàn",               class: "11A3" },
  { id: "HS034", name: "Thị Quế Trân",                  class: "11A3" },
  { id: "HS035", name: "Phạm Minh Trí",                 class: "11A3" },
  { id: "HS036", name: "Nguyễn Minh Triết",             class: "11A3" },
  { id: "HS037", name: "Mai Thị Thanh Trúc",            class: "11A3" },
  { id: "HS038", name: "Nguyễn Khắc Việt",              class: "11A3" },
  { id: "HS039", name: "Mai Nguyễn Thuỳ Linh",          class: "11A3" },
];